### PR TITLE
Feature/hero mobile

### PR DESCRIPTION
**Pull request by JFozzie**
Refactor the "Hero" component with its respective mobile and desktop versions.

Modify the following files:

- **hero.hbs**
- **heroTab.hbs**
- **heroTabButton.hbs**
- **_hero.scss**
- **_hero.js**

https://user-images.githubusercontent.com/111401432/201780386-50c10b27-64d6-499c-b1dc-215b54c079c8.mp4

https://user-images.githubusercontent.com/111401432/201780396-867ca662-f314-41b9-8384-e5b7abf2ff1c.mp4

### CODE REVIEW

**Review by jrmahechad — CHANGES_REQUESTED** [review]
Hi @JFozzie It looks great. I just merged the fix for the image aspect ratio. Can you update and resolve conflicts?


`height: calc(5 * ((min(1440px, 100vw) - 624px) / 12) + 192px);`

**Review by jrmahechad — APPROVED** [review]

**Review by jsebax — APPROVED** [review]
@JFozzie Please review this issue. The shapes on desktop are causing an overflow in the page.
image

**Review by jsebax — CHANGES_REQUESTED** [review]
Please review the previous issue. I think it can be fixed by adding `overflow: hidden;` to the class `.hero`.

**Review by jsebax — APPROVED** [review]

**Comment by jsebax** [comment]
Please resolve merge conflicts

**Pull request merged**
